# This happens when someone damages the player and ends when the specified time has passed
on-tag:
  text: '&bCombat: &7&l[&a{left}&c{right}&7&l] &r&e{seconds} &b[sec]'
  sound:
    type: NONE
    volume: 1
    pitch: 1
# This happens when the specified time has passed
on-untag:
  text: '&aYou can now safely disconnect'
  sound:
    type: NONE
    volume: 1
    pitch: 1
character: '||'
time-untag: 10
plugin-check: true
send-damager: true