name: CombatActionBar
main: me.jaime29010.combatactionbar.Main
version: 1.5.5
author: jaime29010
commands:
  combatactionbar:
    description: Command for reloading the config of CombatActionBar
    permission: combatactionbar.reload
    aliases: [cab]
