name: CombatActionBar
main: me.jaime29010.combatactionbar.Main
version: ${project.version}
author: jaime29010
softdepend: [AntiCombatLog, CombatLog, CombatTag, CombatTagPlus, GriefPrevention, PvPManager, ActionBarAPI]
commands:
  combatactionbar:
    description: Command for reloading the config of CombatActionBar
    permission: combatactionbar.reload
    aliases: [combatab, cab]