name: CombatActionBar
main: me.jaimemartz.combatactionbar.CombatActionBar
version: ${project.version}
author: jaime29010
softdepend: [AntiCombatLog, CombatLog, CombatTag, CombatTagPlus, GriefPrevention, PvPManager, ActionBarAPI]
commands:
  combatactionbar:
    description: Command for reloading the config of CombatActionBar
    permission: combatactionbar.reload
    aliases: [combatab, cab]
permissions:
  combatactionbar.nobar:
    description: Use this permission when you do not want to receive the action bar
    default: false